# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pysrb4w.ui'
#
# Created: Tue Sep 12 15:32:27 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbSubs = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSubs.sizePolicy().hasHeightForWidth())
        self.cmbSubs.setSizePolicy(sizePolicy)
        self.cmbSubs.setMinimumSize(QtCore.QSize(240, 0))
        self.cmbSubs.setEditable(True)
        self.cmbSubs.setObjectName("cmbSubs")
        self.horizontalLayout.addWidget(self.cmbSubs)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbSort = QtGui.QComboBox(self.centralwidget)
        self.cmbSort.setObjectName("cmbSort")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.horizontalLayout.addWidget(self.cmbSort)
        self.btnLoad = QtGui.QPushButton(self.centralwidget)
        self.btnLoad.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16/res/16/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoad.setIcon(icon)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        spacerItem = QtGui.QSpacerItem(40, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnFontInc = QtGui.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16/res/16/font-inc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFontInc.setIcon(icon1)
        self.btnFontInc.setAutoRaise(True)
        self.btnFontInc.setObjectName("btnFontInc")
        self.horizontalLayout_3.addWidget(self.btnFontInc)
        self.btnFontDec = QtGui.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16/res/16/font-dec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFontDec.setIcon(icon2)
        self.btnFontDec.setAutoRaise(True)
        self.btnFontDec.setObjectName("btnFontDec")
        self.horizontalLayout_3.addWidget(self.btnFontDec)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.btnLink = QtGui.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16/res/16/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLink.setIcon(icon3)
        self.btnLink.setObjectName("btnLink")
        self.horizontalLayout.addWidget(self.btnLink)
        spacerItem1 = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnVoteUp = QtGui.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/16/res/16/vote-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoteUp.setIcon(icon4)
        self.btnVoteUp.setCheckable(True)
        self.btnVoteUp.setAutoRaise(True)
        self.btnVoteUp.setObjectName("btnVoteUp")
        self.horizontalLayout_2.addWidget(self.btnVoteUp)
        self.btnVoteDn = QtGui.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16/res/16/vote-dn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoteDn.setIcon(icon5)
        self.btnVoteDn.setCheckable(True)
        self.btnVoteDn.setAutoRaise(True)
        self.btnVoteDn.setObjectName("btnVoteDn")
        self.horizontalLayout_2.addWidget(self.btnVoteDn)
        self.btnSaved = QtGui.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/16/res/16/saved.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaved.setIcon(icon6)
        self.btnSaved.setCheckable(True)
        self.btnSaved.setChecked(False)
        self.btnSaved.setAutoRaise(True)
        self.btnSaved.setObjectName("btnSaved")
        self.horizontalLayout_2.addWidget(self.btnSaved)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.btnHide = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHide.sizePolicy().hasHeightForWidth())
        self.btnHide.setSizePolicy(sizePolicy)
        self.btnHide.setMinimumSize(QtCore.QSize(64, 0))
        self.btnHide.setMaximumSize(QtCore.QSize(64, 16777215))
        self.btnHide.setObjectName("btnHide")
        self.horizontalLayout.addWidget(self.btnHide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.txtBody = QtGui.QTextBrowser(self.centralwidget)
        self.txtBody.setObjectName("txtBody")
        self.verticalLayout.addWidget(self.txtBody)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SRB4W", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Sub", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(0, QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hot", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(2, QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFontInc.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFontDec.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLink.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoteUp.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoteDn.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaved.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHide.setText(QtGui.QApplication.translate("MainWindow", "Hide", None, QtGui.QApplication.UnicodeUTF8))

import pysrb4w_rc
