# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pysrb4w.ui'
#
# Created: Mon Mar 19 17:43:42 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbSubs = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbSubs.sizePolicy().hasHeightForWidth())
        self.cmbSubs.setSizePolicy(sizePolicy)
        self.cmbSubs.setMinimumSize(QtCore.QSize(200, 22))
        self.cmbSubs.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cmbSubs.setEditable(True)
        self.cmbSubs.setObjectName("cmbSubs")
        self.horizontalLayout.addWidget(self.cmbSubs)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cmbSort = QtGui.QComboBox(self.centralwidget)
        self.cmbSort.setMinimumSize(QtCore.QSize(0, 22))
        self.cmbSort.setMaximumSize(QtCore.QSize(16777215, 22))
        self.cmbSort.setObjectName("cmbSort")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.cmbSort.addItem("")
        self.horizontalLayout.addWidget(self.cmbSort)
        self.btnLoad = QtGui.QPushButton(self.centralwidget)
        self.btnLoad.setMinimumSize(QtCore.QSize(28, 24))
        self.btnLoad.setMaximumSize(QtCore.QSize(28, 24))
        self.btnLoad.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16/res/16/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLoad.setIcon(icon)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnFontInc = QtGui.QToolButton(self.centralwidget)
        self.btnFontInc.setMinimumSize(QtCore.QSize(28, 24))
        self.btnFontInc.setMaximumSize(QtCore.QSize(28, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16/res/16/font-inc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFontInc.setIcon(icon1)
        self.btnFontInc.setAutoRaise(False)
        self.btnFontInc.setObjectName("btnFontInc")
        self.horizontalLayout_3.addWidget(self.btnFontInc)
        self.btnFontDec = QtGui.QToolButton(self.centralwidget)
        self.btnFontDec.setMinimumSize(QtCore.QSize(28, 24))
        self.btnFontDec.setMaximumSize(QtCore.QSize(28, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16/res/16/font-dec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFontDec.setIcon(icon2)
        self.btnFontDec.setAutoRaise(False)
        self.btnFontDec.setObjectName("btnFontDec")
        self.horizontalLayout_3.addWidget(self.btnFontDec)
        spacerItem = QtGui.QSpacerItem(16, 16, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnVoteUp = QtGui.QToolButton(self.centralwidget)
        self.btnVoteUp.setMinimumSize(QtCore.QSize(28, 24))
        self.btnVoteUp.setMaximumSize(QtCore.QSize(28, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16/res/16/vote-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoteUp.setIcon(icon3)
        self.btnVoteUp.setCheckable(True)
        self.btnVoteUp.setAutoRaise(False)
        self.btnVoteUp.setObjectName("btnVoteUp")
        self.horizontalLayout_2.addWidget(self.btnVoteUp)
        self.btnVoteDn = QtGui.QToolButton(self.centralwidget)
        self.btnVoteDn.setMinimumSize(QtCore.QSize(28, 24))
        self.btnVoteDn.setMaximumSize(QtCore.QSize(28, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/16/res/16/vote-dn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVoteDn.setIcon(icon4)
        self.btnVoteDn.setCheckable(True)
        self.btnVoteDn.setChecked(False)
        self.btnVoteDn.setAutoRaise(False)
        self.btnVoteDn.setObjectName("btnVoteDn")
        self.horizontalLayout_2.addWidget(self.btnVoteDn)
        self.btnSaved = QtGui.QToolButton(self.centralwidget)
        self.btnSaved.setMinimumSize(QtCore.QSize(28, 24))
        self.btnSaved.setMaximumSize(QtCore.QSize(28, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16/res/16/saved.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaved.setIcon(icon5)
        self.btnSaved.setCheckable(True)
        self.btnSaved.setChecked(False)
        self.btnSaved.setAutoRaise(False)
        self.btnSaved.setObjectName("btnSaved")
        self.horizontalLayout_2.addWidget(self.btnSaved)
        self.btnLink = QtGui.QToolButton(self.centralwidget)
        self.btnLink.setMinimumSize(QtCore.QSize(28, 24))
        self.btnLink.setMaximumSize(QtCore.QSize(28, 24))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/16/res/16/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLink.setIcon(icon6)
        self.btnLink.setAutoRaise(False)
        self.btnLink.setObjectName("btnLink")
        self.horizontalLayout_2.addWidget(self.btnLink)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.btnHide = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHide.sizePolicy().hasHeightForWidth())
        self.btnHide.setSizePolicy(sizePolicy)
        self.btnHide.setMinimumSize(QtCore.QSize(64, 24))
        self.btnHide.setMaximumSize(QtCore.QSize(64, 24))
        self.btnHide.setCheckable(False)
        self.btnHide.setChecked(False)
        self.btnHide.setObjectName("btnHide")
        self.horizontalLayout.addWidget(self.btnHide)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.txtBody = QtGui.QTextBrowser(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.txtBody.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.txtBody.setFont(font)
        self.txtBody.setObjectName("txtBody")
        self.verticalLayout.addWidget(self.txtBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SRB4W", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Sub.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Sort", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(0, QtGui.QApplication.translate("MainWindow", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hot", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbSort.setItemText(2, QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFontInc.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFontDec.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoteUp.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVoteDn.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaved.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLink.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHide.setText(QtGui.QApplication.translate("MainWindow", "Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.txtBody.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:15px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt; background-color:#ffffff;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))

import pysrb4w_rc
